name: Evaluate Model

on:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed

jobs:
  evaluate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Evaluate model
        run: |
          python evaluate_model.py
