name: Model Evaluation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  evaluate_model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run model evaluation
      run: |
        python evaluate_model.py  # Si vous avez un script spécifique pour évaluer les performances du modèle

    - name: Save evaluation metrics
      uses: actions/upload-artifact@v2
      with:
        name: model-evaluation-metrics
        path: evaluation_metrics.json  # Sauvegarde des métriques de performance du modèle
